# dev_reader.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: clever-apps-namespace
  name: developer
rules:
  - apiGroups: [""]
    resources: ["pods", "logs"]
    verbs: ["get", "list", "watch"]